# Allow local access
local   all             all                                     trust

# Allow replication
host    replication     replicator             0.0.0.0/0               md5

# Allow normal connections
host    all             all             0.0.0.0/0               md5
