# Allow local access
local   all             all                                     trust

# Allow replication
host    replication     replicator             0.0.0.0/0               scram-sha-256

# Allow normal connections
host    all             all             0.0.0.0/0               scram-sha-256
